server:
  port: ${PORT}

spring:
  main:
    banner-mode: console

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Opciones: create, update, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always  # Permite cargar scripts SQL al inicio (opcional)

security:
  jwt:
    key:
      private: ${JWT_PRIVATE_KEY}  # Se debe definir en variables de entorno
    user:
      generator: "auth-service"
